[build]
  base = "."  # Use the root directory for the build
  publish = "out"  # Specify the directory to publish the static files
  command = "next build"  # Only run `next build` here, remove `next export`
